### PR TITLE
Allow to specify SIMPLECOV_BUILDKITE_CONTEXT via buildkite pipeline env

### PR DESCRIPTION
**Pull request by savka2017**
Fix for the issue: [Rails engines coverage report
](https://github.com/buildkite/simplecov-buildkite/issues/17)

Add ability to specify the app/module/service name via buildkite pipeline env, i.e.:

```yaml
- label: ':rspec: Run test: Main'
    commands:
      - bundle exec rspec
    env:
      SIMPLECOV_BUILDKITE_CONTEXT: "Main app"
 - label: ':rspec: Run test: Engine 1'
    commands:
      - cd engine1 && bundle exec rspec
    env:
      SIMPLECOV_BUILDKITE_CONTEXT: "Engine 1"
```

As a result each app/module/service in project will have its own separate report on buildkite.

### CODE REVIEW

**Comment by Stashchenko** [comment]
Hi @ticky @sj26 @timriley , could you review the fix please?

**Review by Stashchenko — APPROVED** [review]

**Comment by ticky** [comment]
@Stashchenko I no longer work at Buildkite, I would suggest pinging support@buildkite.com if you don't get any traction on this.

**Comment by sj26** [comment]
Hi there - thanks for the PR!

(and hi @ticky! :wave:)

I hear your need, but I'm not sure if the config object is the right way. You'd need to then have a way to parameterize and pass in those configuration options from the layer above.

What if we used ENV variables instead? That's pretty conventional. Would this also solve your need:

https://github.com/buildkite/simplecov-buildkite/compare/add-config-env

**Comment by Stashchenko** [comment]
> Hi there - thanks for the PR!
> 
> (and hi @ticky! 👋)
> 
> I hear your need, but I'm not sure if the config object is the right way. You'd need to then have a way to parameterize and pass in those configuration options from the layer above.
> 
> What if we used ENV variables instead? That's pretty conventional. Would this also solve your need:
> 
> https://github.com/buildkite/simplecov-buildkite/compare/add-config-env

It's ok for us. One minor suggestion, I'd make a control using one ENV['SIMPLECOV_BUILDKITE_CONTEXT'] = 'Module 1' and then use it for title & buildkite context.

**Comment by sj26** [comment]
Contexts are intended to be for machines, so probably should be slug-y .. but I don't think it matters too much.

**Comment by Stashchenko** [comment]
> Contexts are intended to be for machines, so probably should be slug-y .. but I don't think it matters too much.
> 
> Leave it with us :-)

Are you good to go with those changes ? Could you please release if so (or when)?

**Comment by timriley** [comment]
Hi @Stashchenko, thanks for your contributions here! I plan to incorporate this change and make a release next week :)

**Comment by timriley** [comment]
Sorry, I might not get to this this week in the end. I'll aim for next week!

**Comment by Stashchenko** [comment]
> Sorry, I might not get to this this week in the end. I'll aim for next week!

Hi @timriley , any updates ?

**Comment by timriley** [comment]
Thanks for your patience here, @Stashchenko! I'm going to get this done this week. First step will be merging your PR here. Next, I think I might make an adjustment to use distinct env vars like @sj26 demonstrated in his example. I'll be sure to ping you again once this is all done and released.

**Review by timriley — APPROVED** [review]

**Comment by timriley** [comment]
Hi @Stashchenko, this is now released as v0.3.0 :)

**Pull request merged**
